---

- name: Stopping proftpd and disabled service
  systemd:
    name: proftpd
    state: stopped
    enabled: no
  tags: proftpd


- name: Remove firewalld rules for Proftpd
  firewalld:
    service: ftp
    permanent: true
    immediate: true
    state: disabled
  tags: proftpd


- name: Remove allow_ftpd_full_access flag on and keep it persistent across reboots
  seboolean:
    name: allow_ftpd_full_access
    state: no
    persistent: no
  tags: proftpd



- name: Remove proftpd packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - proftpd
    - openssl
    - proftpd-utils
    - proftpd-mysql
    - libsemanage-python
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: proftpd


- name: Remove proftpd packages
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - proftpd
    - openssl
    - proftpd-utils
    - proftpd-mysql
      - python3-libsemanage
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: proftpd

- name: Remove proftpd.conf.bak
  file:
    state: absent
    path: /etc/proftpd.conf.bak
  tags: proftpd


- name: Remove proftpd.conf
  file:
    state: absent
    path: /etc/proftpd.conf
  tags: proftpd


